[2022-09-03T13:00:01.116+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: weather_data.create_table scheduled__2022-09-03T12:00:00+00:00 [queued]>
[2022-09-03T13:00:01.127+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: weather_data.create_table scheduled__2022-09-03T12:00:00+00:00 [queued]>
[2022-09-03T13:00:01.128+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-03T13:00:01.130+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-03T13:00:01.131+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-03T13:00:01.141+0000] {taskinstance.py:1389} INFO - Executing <Task(PostgresOperator): create_table> on 2022-09-03 12:00:00+00:00
[2022-09-03T13:00:01.146+0000] {standard_task_runner.py:52} INFO - Started process 77 to run task
[2022-09-03T13:00:01.148+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'weather_data', 'create_table', 'scheduled__2022-09-03T12:00:00+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp8c9yoh6b', '--error-file', '/tmp/tmp39q3u4je']
[2022-09-03T13:00:01.150+0000] {standard_task_runner.py:80} INFO - Job 263: Subtask create_table
[2022-09-03T13:00:01.191+0000] {task_command.py:371} INFO - Running <TaskInstance: weather_data.create_table scheduled__2022-09-03T12:00:00+00:00 [running]> on host f432245fdbd9
[2022-09-03T13:00:01.241+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_data
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-03T12:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-03T12:00:00+00:00
[2022-09-03T13:00:01.252+0000] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-09-03T13:00:01.257+0000] {sql.py:315} INFO - Running statement: create table if not exists weather(
                id              serial primary key,
                name            varchar(50),
                temp            float,
                temp_feels_like float,
                temp_min        float,
                temp_max        float,
                description     varchar(50),
                wind_speed      float,
                humidity        float,
                pressure        smallint,
                sunset          int,
                sunrise         int
            ), parameters: None
[2022-09-03T13:00:01.259+0000] {postgres.py:94} INFO - NOTICE:  relation "weather" already exists, skipping

[2022-09-03T13:00:01.270+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=weather_data, task_id=create_table, execution_date=20220903T120000, start_date=20220903T130001, end_date=20220903T130001
[2022-09-03T13:00:01.323+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-03T13:00:01.356+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
